### ISSUE TITLE
Building issues with docker

### ISSUE THREAD

**Issue by skhrlx** [daijro/camoufox#1]
While using docker, it always gives an error for aria2c (which is installed, If I type aria2c it shows an help message)

Another error that occurs is when it checks and "force" install git and all other dependencies, it can't find aria2c too, but I can bypass this error by removing it from Dockerfile, but this seconded one which is quoted, no.

Command used on a clean git clone: docker build -t camoufox-builder .

System OS: Ubuntu 22/24gb ram/1tb ssd

I can successfully build the Linux camoufox, only the windows versions is giving me this headache

```
=> ERROR [5/5] RUN make setup-minimal &&     make mozbootstrap &&     0.3s
------
 > [5/5] RUN make setup-minimal &&     make mozbootstrap &&     mkdir /app/dist:
0.275 # Note: Only docker containers are intended to run this directly.
0.276 # Run this before `make dir` or `make build` to avoid setting up a local git repo.
0.277 if [ ! -f firefox-129.0.source.tar.xz ]; then \
0.277   make fetch; \
0.277 fi
0.279 make[1]: Entering directory '/app'
0.283 aria2c -x16 -s16 -k1M -o firefox-129.0.source.tar.xz "https://archive.mozilla.org/pub/firefox/releases/129.0/source/firefox-129.0.source.tar.xz"; \
0.283
0.284 /bin/sh: 1: aria2c: not found
0.284 make[1]: *** [Makefile:33: fetch] Error 127
0.285 make[1]: Leaving directory '/app'
0.288 make: *** [Makefile:38: setup-minimal] Error 2
------
Dockerfile:18
--------------------
  17 |     # Fetch Firefox & apply initial patches
  18 | >>> RUN make setup-minimal && \
  19 | >>>     make mozbootstrap && \
  20 | >>>     mkdir /app/dist
  21 |
--------------------
ERROR: failed to solve: process "/bin/sh -c make setup-minimal &&     make mozbootstrap &&     mkdir /app/dist" did not complete successfully: exit code: 2
root@vmi1873132:~/camoufox# aria2c
Specify at least one URL.
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.
```

**Comment by daijro** [comment]
Fixed in the latest commit. `aria2c` was an invalid package name, it should have been `aria2`.

**Comment by skhrlx** [comment]
I'm not going to spamming a lot of issues, but, while trying to build for windows again, I got an error:
![Screenshot_20240816_041355_JuiceSSH](https://github.com/user-attachments/assets/b8d58be7-fea9-4a80-ad49-f2569287c7f5)
Apparently, I solved that by simple installing "apt-get install rustc"
And after "Apparently" solving this (idk if it really worked), I just got some new errors:
![Screenshot_20240816_060154_JuiceSSH](https://github.com/user-attachments/assets/91ab1402-69c3-4c00-9f3d-654271e7fe99)
Why it is trying to download go again? I have it successfully already installed and working (checked by running ```go version``` command which returns that i have it on 1.23)

**Comment by daijro** [comment]
> Apparently, I solved that by simple installing "apt-get install rustc"

Thanks for letting me know. Not sure why this wasn't done automatically by Firefox's `mach bootstrap`. I will go ahead and add it to the Dockerfile.

Unfortunately Firefox's build process can be unpredictable for different OS targets. I hope it didn't cause you too much trouble.

> Why it is trying to download go again?

Go tries to download its toolchains on the spot when building. I was able to fix the `toolchain not found` issues in Docker after changing `go 1.23` to `go 1.23.0` in go.mod.
