### ISSUE TITLE
Invalid `navigator.productSub` value

### ISSUE THREAD

**Issue by DeviousStoat** [daijro/camoufox#105]
### Describe the bug:

The value of `navigator.productSub` seems invalid. I always get `20030107` but

On the [mozilla doc page](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/productSub) it says:
```
On Apple Safari and Google Chrome this property always returns 20030107.

On Firefox, this property always returns 20100101.
```

And on my regular firefox browser I do always get `20100101` too.

So I think it should be `20100101`, matching the value in the user agent.

It might be a browserforge issue as well.

### Version:

```
Pip package:    v0.4.3
Camoufox:       v132.0.2-beta.17 (Up to date!)
```

**Comment by daijro** [comment]
Thank you for letting me know. Starting in 0.4.4, the BrowserForge productSub value will be ignored.
