### ISSUE TITLE
Option to use exact user-specified fonts without loading from fonts.json

### ISSUE THREAD

**Issue by cda2** [daijro/camoufox#109]
### Describe the feature:

Is there a way to use the exact list of fonts entered by the user in the "fonts" key-value pair?

### Is your feature request related to a problem? Please describe.

Hello,

First of all, thank you for developing such an excellent library.

I am experiencing some difficulties with the [logic that applies fonts](https://github.com/daijro/camoufox/blob/99801bd139d99cff8159ef0ecad81876552d6da8/pythonlib/camoufox/utils.py#L174-L185).
According to the code, it appears that when generating the browser by specifying the "fonts" key value, the fonts are combined with the JSON values corresponding to the "os" value, which is determined before the font-related logic (maybe from [get_target_os](https://github.com/daijro/camoufox/blob/99801bd139d99cff8159ef0ecad81876552d6da8/pythonlib/camoufox/utils.py#L132-L139) function).
However, due to this logic, rarely system using fonts that do not exist on the system, and it seems that we are being blocked by some anti-bot solutions that use font fingerprinting.
Especially in Linux environments, where there are many limitations on font types, having this feature would be particularly useful.

Thank you.

**Comment by daijro** [comment]
Hello,

As of 0.4.4, I've added a `custom_fonts_only` parameter to only apply fonts listed in the `fonts` parameter.


Hope this helps :+1:

**Comment by cda2** [comment]
Much appreciated. Thanks for your help!
