### ISSUE TITLE
With persistent_context=True, Two windows are opened (one blank, one with the URL)

### ISSUE THREAD

**Issue by kai2008** [daijro/camoufox#119]
### Describe the bug:

When the `persistent_context` is set to `true` with the following options:

```python
persistent_context=True,
user_data_dir=user_data_dir,
```

The following code is executed:
```
page = browser.new_page()
page.goto("https://www.browserscan.net/")
```

#### Actual Behavior:
This results in two windows being opened:
A blank page in a new window.
A page that successfully navigates to the specified URL.

#### Expected Behavior
Only one page should open and navigate to the specified URL when persistent_context is set to true.

#### Summary
With `persistent_context=True`: Two windows are opened (one blank, one with the URL).
Without `persistent_context=True`: Only one page opens and navigates to the URL.

### Screenshots:
![camoufox_bug](https://github.com/user-attachments/assets/f78783f5-63e9-4256-a364-39d079136682)

### To Reproduce:

```python
persistent_context=True,
user_data_dir=user_data_dir,
```

The following code is executed:
```
page = browser.new_page()
page.goto("https://www.browserscan.net/")
```

### Version:

```
python3 -m camoufox version
Pip package:    v0.4.5
Camoufox:       v133.0-beta.18 (Up to date!)
```

**Comment by kai2008** [comment]
It doesn’t look like a bug.
Before creating a new page, first check if any existing pages are available by using browser.pages.
If there are existing pages (which is likely in persistent context mode), reuse the first page. That resolved my issue.

**Comment by webee** [comment]
In fact, when you use persistent_context, browser is actually a BrowserContext. The lib created a page and return the context behind the scenes.
