### ISSUE TITLE
how to use humanize cursor property how to enable

### ISSUE THREAD

**Issue by francadossantosjoaofelipe35** [daijro/camoufox#22]
pleas help

**Comment by daijro** [comment]
To use humanized cursor movement in the Python library, first, confirm you are on the latest beta:

```bash
camoufox fetch
```

Then, you can pass config properties like this:

```python
with Camoufox(
    headless=False,
    config={
        "humanize": True
    }
) as browser:
    page = browser.new_page()
    page.goto("https://www.google.com/")
    ...
```

**Comment by desoforgit** [comment]
> pleas help


You can do it by adding the humanize property in the config like this 


```
from camoufox.sync_api import Camoufox

with Camoufox(
    config={
        'humanize': True,
    }
) as browser:
    page = browser.new_page()
    page.goto("https://www.example.com/")
```

**Comment by francadossantosjoaofelipe35** [comment]
this is my code from camoufox.sync_api import Camoufox
from playwright_recaptcha import recaptchav2
from browserforge.fingerprints import FingerprintGenerator

fg = FingerprintGenerator(browser='chrome', os='windows')

with Camoufox(
    humanize=True,
    geoip=True,
    fingerprint=fg.generate(),
    config = {
        "humanize": True,               # Ativa o movimento humano do cursor
    },
    proxy={
        'server': 'http://geo.iproyal.com:12321',
        'username': '',
        'password': '-us'
    },
) as browser:
    page = browser.new_page()
    page.goto("https://www.google.com/recaptcha/api2/demo")

    with recaptchav2.SyncSolver(page) as solver:
        token = solver.solve_recaptcha(wait=True)
        print(token) and i getting this error camoufox.exceptions.UnknownProperty: Unknown property humanize in config i installed the camoufox with pip install camoufox and i alrealdy tried to do pip install --upgrade camoufox

**Comment by daijro** [comment]
> this is my code
> and i getting this error camoufox.exceptions.UnknownProperty: Unknown property humanize in config i installed the camoufox with pip install camoufox and i alrealdy tried to do pip install --upgrade camoufox
> ```
> from camoufox.sync_api import Camoufox
> from playwright_recaptcha import recaptchav2
> from browserforge.fingerprints import FingerprintGenerator
> 
> fg = FingerprintGenerator(browser='chrome', os='windows')
> 
> with Camoufox(
>     humanize=True,
>     geoip=True,
>     fingerprint=fg.generate(),
>     config = {
>         "humanize": True,               # Ativa o movimento humano do cursor
>     },
>     proxy={
>         'server': 'http://geo.iproyal.com:12321',
>         'username': '',
>         'password': '-us'
>     },
> ) as browser:
>     page = browser.new_page()
>     page.goto("https://www.google.com/recaptcha/api2/demo")
> 
>     with recaptchav2.SyncSolver(page) as solver:
>         token = solver.solve_recaptcha(wait=True)
>         print(token)

Could you run `camoufox version` and send the output?

Also note, Camoufox doesn't support injecting Chrome fingerprints. This will likely lead to detection.

**Comment by francadossantosjoaofelipe35** [comment]
C:\Users\joao\Documents>camoufox version
Pip package:    v0.2.4
Camoufox:       v130.0.1-beta.10 (Up to date!)

**Comment by daijro** [comment]
Thanks. I see the issue now, I'll work on a quick patch for the Pypi library

**Comment by francadossantosjoaofelipe35** [comment]
C:\Users\joao>camoufox remove
Cleaning up cache: C:\Users\joao\AppData\Local\camoufox\camoufox\Cache
GeoIP database removed.

C:\Users\joao>camoufox fetch
Fetching Camoufox binaries v130.0.1-beta.10...
Downloading package: https://github.com/daijro/camoufox/releases/download/v130.0.1-beta.10/camoufox-130.0.1-beta.10-win.x86_64.zip
100%|██████████████████████████████████████████████████████████████████████████████| 556M/556M [00:11<00:00, 47.4MiB/s]
Extracting Camoufox: C:\Users\joao\AppData\Local\camoufox\camoufox\Cache
100%|████████████████████████████████████████████████████████████████████████████████| 511/511 [00:11<00:00, 44.13it/s]

Camoufox successfully installed.
Downloading GeoIP database: 100%|████████████████████████████████████████████████| 60.3M/60.3M [00:01<00:00, 42.3MiB/s]

C:\Users\joao>cd documents

C:\Users\joao\Documents>python solver.py
Downloading addon (UBO): 100%|███████████████████████████████████████████████████| 3.96M/3.96M [00:00<00:00, 27.7MiB/s]
Extracting addon (UBO): 100%|███████████████████████████████████████████████████████| 620/620 [00:00<00:00, 628.22it/s]
Downloading addon (BPC): 100%|██████████████████████████████████████████████████████| 226k/226k [00:00<00:00, 373kiB/s]
Extracting addon (BPC): 100%|████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 2743.71it/s]
Traceback (most recent call last):
  File "C:\Users\joao\Documents\solver.py", line 7, in <module>
    with Camoufox(
  File "C:\Users\joao\AppData\Local\Programs\Python\Python39\lib\site-packages\camoufox\sync_api.py", line 23, in __enter__
    self.browser = NewBrowser(self._playwright, **self.launch_options)
  File "C:\Users\joao\AppData\Local\Programs\Python\Python39\lib\site-packages\camoufox\sync_api.py", line 114, in NewBrowser
    return playwright.firefox.launch(**opt)
TypeError: launch() got an unexpected keyword argument 'humanize'

**Comment by francadossantosjoaofelipe35** [comment]
the problem continues

**Comment by daijro** [comment]
> TypeError: launch() got an unexpected keyword argument 'humanize'

The `humanize` parameter has not been added yet.

**Comment by francadossantosjoaofelipe35** [comment]
what

**Comment by francadossantosjoaofelipe35** [comment]
this shit are not working

**Comment by francadossantosjoaofelipe35** [comment]
update: now are working sorry, working after camoufox remove then camoufox fetch
