### ISSUE TITLE
detected in imperva, this camoufox its potentialy detected

### ISSUE THREAD

**Issue by francadossantosjoaofelipe35** [daijro/camoufox#29]
![{B8E4E83D-9ED6-432C-9E6F-903E0D1D812A}](https://github.com/user-attachments/assets/16bcdfdd-bc2c-402c-a9b2-c5b578e63e20)
after some reloading in the page, detected browser

**Comment by daijro** [comment]
Hello, could you provide the Camoufox initialization you used in your Python script, and the output of `camoufox version`?

**Comment by daijro** [comment]
> after some reloading in the page, detected browser

How many times have you reloaded? Are you using proxies?

**Comment by francadossantosjoaofelipe35** [comment]
parece que resolvido após usar

```
            block_webrtc=True,
            fingerprint=fg.generate(),
```
