### ISSUE TITLE
how to solve this warning

### ISSUE THREAD

**Issue by francadossantosjoaofelipe35** [daijro/camoufox#30]
fg = FingerprintGenerator(browser='firefox', os='windows')
    try:
        # Usar Camoufox para navegar e preencher o formulário
        with Camoufox(
            headless=False,
            block_webrtc=True,
            fingerprint=fg.generate(),
            config = {
                "humanize": True,               # Ativa o movimento humano do cursor
            },
C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\camoufox\utils.py:199: UserWarning: Passing your own fingerprint is not recommended. BrowserForge fingerprints are automatically generated within Camoufox based on the provided `os` and `screen` constraints.
  warnings.warn(

**Comment by daijro** [comment]
Instead of generating your own fingerprint, it's better to pass in the OS directly into the `Camoufox` initialization to generate a fingerprint for you.

```py
with Camoufox(
    headless=False,
    block_webrtc=True,
    os='windows',
    humanize=True,
```
