### ISSUE TITLE
Allow setting `locale` (manual `geoip`)

### ISSUE THREAD

**Issue by tobwen** [daijro/camoufox#33]
### Describe the feature:

Please add `locale=[countrycode]` as parameter to allow the manual selection of the browser's language and the user's longitude, latitude, timezone, country, locale, & spoof the WebRTC IP address with help of the _GeoIP-DB_.

### Is your feature request related to a problem? Please describe.

`geoip=True` does a true job, but for some projects the browser identity must be fixed and I'm not aware if setting this before starting _camoufox_ will make it through to the browser:

``` python
import locale
locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')
```

**Comment by daijro** [comment]
Hello!

Camoufox does have a `locale` parameter. It takes any standard locale code ([here's a list](https://simplelocalize.io/data/locales/)), and parses it with the language-tags library:

```python
with Camoufox(locale='en-US'):
    ...
```

Were you looking for a different implementation?

**Comment by tobwen** [comment]
What the heck? I really didn't see it :-) Thanks!

Is there a list of parameters?

**Comment by tobwen** [comment]
> Were you looking for a different implementation?

Maybe I closed this too fix (sorry, too early in the morning). Does `locale` do the same thing as `geoip` does when it detects a country?

**Comment by daijro** [comment]
> Is there a list of parameters?

Any standard locale code works, in the format `language-script-country`, where `language` and `country` are required. For example, `de-DE` or `zh-Hans-CN` to specify to `Hans` script.

> Does locale do the same thing as geoip does when it detects a country?

Do you mean the auto-language selection? It doesn't have that at the moment, but I could add it if you'd like to allow passing `locale='US'` without specifying the language.

**Comment by tobwen** [comment]
> > Is there a list of parameters?
> 
> Any standard locale code works

I mean a complete list of parameters, like `headless`, `proxy`, etc. supported by _camoufox_. I wasn't aware that `locale` exists as a parameter :-)
 
> > Does locale do the same thing as geoip does when it detects a country?
> 
> Do you mean the auto-language selection? It doesn't have that at the moment, but I could add it if you'd like to allow passing `locale='US'` without specifying the language.

At the moment `geoip` recognises the country based on the IP address and makes changes to the identification of the browser. It would be great if all these changes were also made by `locale`, like

- longitude
- latitude
- timezone
- country
- spoof the WebRTC IP address

So actually `geoip` the other way round.

**Comment by daijro** [comment]
> I mean a complete list of parameters, like headless, proxy, etc. supported by camoufox. I wasn't aware that locale exists as a parameter :-)

Oh haha, I have it in the Parameters dropdown under Usage in the README (see [here](https://github.com/daijro/camoufox/tree/main/pythonlib#usage)).
 
> At the moment `geoip` recognises the country based on the IP address and makes changes to the identification of the browser. It would be great if all these changes were also made by `locale`, like
> 
> * longitude
> * latitude
> * timezone
> * country
> * spoof the WebRTC IP address
> 
> So actually `geoip` the other way round.

I could add that, but it could cause detection since the user's IP wouldn't match the browser's claimed geolocation.

For example, if I set my locale to zh-CN, my longitude/latitude, timezone, and country would spoof to be located in China, while my IP says I'm in the US.

**Comment by tobwen** [comment]
> Oh haha, I have it in the Parameters dropdown under Usage in the README (see [here](https://github.com/daijro/camoufox/tree/main/pythonlib#usage)).

Holy! Thanks a lot. I really didn't see this. Small, but important.
 
> I could add that, but it could cause detection since the user's IP wouldn't match the browser's claimed geolocation.
> 
> For example, if I set my locale to zh-CN, my longitude/latitude, timezone, and country would spoof to be located in China, while my IP says I'm in the US.

Yeah, you're right. I just thought about VPN or proxy use where your browser also has another locale than the IP. But you're right - in some constellations this could have negative effects.
