### ISSUE TITLE
How to return to the page before clicking

### ISSUE THREAD

**Issue by satanmp** [daijro/camoufox#34]
page.go_back() not work

**Comment by daijro** [comment]
Hello,

go_back works locally for me. Could you provide the error/a snippet of your script that I can reproduce?

**Comment by satanmp** [comment]
> Hello,
> 
> go_back works locally for me. Could you provide the error/a snippet of your script that I can reproduce?
> 
> Note: Camoufox limits the amount of pages in the bfcache (back/forward cache) to save memory, so it could be possible that your cache was cleared.

   with Camoufox(headless=False, geoip=True,i_know_what_im_doing=True,
                humanize = True,
                os=('windows', 'macos', 'linux'),
                slow_mo=100, block_images=True,) as browser:
        page = browser.new_page()
        try:
            page.goto("https://www.google.com/")

            input_xpath = "xpath=//textarea[@class='gLFyf']"
            page.locator(input_xpath).wait_for(timeout=20000)
            page.locator(input_xpath).type(keyword, delay=100)


            time.sleep(random.randint(2, 5))

            page.locator("xpath=//h3[contains(text(),'NGINX 配置')]").click()

            time.sleep(10)
            page.go_back()

**Comment by satanmp** [comment]
> Hello,
> 
> go_back works locally for me. Could you provide the error/a snippet of your script that I can reproduce?
> 
> Note: Camoufox limits the amount of pages in the bfcache (back/forward cache) to save memory, so it could be possible that your cache was cleared.

`
    with Camoufox(headless=False, geoip=True,i_know_what_im_doing=True,
                humanize = True,
                os=('windows', 'macos', 'linux'),
                slow_mo=100, block_images=True,) as browser:
            page = browser.new_page()
            try:
                page.goto("https://www.baidu.com/")
    
                input_xpath = "xpath=//*[@id='kw']"
                page.locator(input_xpath).wait_for(timeout=20000)
                page.locator(input_xpath).type('nginx', delay=100)
    
                page.locator(input_xpath).press("Enter")
    
                result_pxath = "xpath=//*[@id='content_left']"
                page.locator(result_pxath).wait_for(state='attached', timeout=20000)
    
                result_count = page.locator("xpath=//h3/a[contains(@href,'http://www.baidu.com/link?url=')]").count()
                click_count = random.randint(1, result_count)
                page.locator(f"xpath=(//h3/a[contains(@href,'http://www.baidu.com/link?url=')])[{click_count}]").click()
                time.sleep(random.randint(2, 5))
    
                page.go_back()



`

**Comment by satanmp** [comment]
> Hello,
> 
> go_back works locally for me. Could you provide the error/a snippet of your script that I can reproduce?
> 
> Note: Camoufox limits the amount of pages in the bfcache (back/forward cache) to save memory, so it could be possible that your cache was cleared.

It's work,thank you.
