### ISSUE TITLE
locale error

### ISSUE THREAD

**Issue by satanmp** [daijro/camoufox#36]
### Describe the bug:

Under the default settings, the following error is reported:
(<class 'ValueError'>, ValueError("Invalid locale: 'zh_Hant-HK'. All locales must be in the format of language[-script][-region]"), <traceback object at 0x000002A537CB11C0>)

### Screenshots:

![图片](https://github.com/user-attachments/assets/979d0031-dc50-4e4a-9410-1cf78d97cec2)

### To Reproduce:

    with Camoufox(headless=False, geoip=True,i_know_what_im_doing=True,
                config = {
                    "fonts": get_random_font_name(),
                    # "locale:language": "zh-CN,zh",
                    # "navigator.userAgent": useragent,
                },
                humanize = True,
                os=('windows', 'macos', 'linux'),
                slow_mo=100, block_images=True,) as browser:
        context = browser.new_context()
        page = context.new_page()

### Version:

beat.11

**Comment by daijro** [comment]
Fix has been added in the latest version of the python library.
