### ISSUE TITLE
Playwright windows problem

### ISSUE THREAD

**Issue by MaxAndolini** [daijro/camoufox#4]
I tried the sample code with the latest Windows release and it does not work at all, even though the latest version of Playwright is installed.

![image](https://github.com/user-attachments/assets/45afdf65-82fb-4273-94c0-197315730830)

**Comment by pim97** [comment]
I have the same issue! On all released versions

**Comment by daijro** [comment]
> I have the same issue! On all released versions

Hello, the Camoufox python api has just been released:
https://github.com/daijro/camoufox/tree/main/pythonlib#camoufox-python-interface

It now supports Windows and (hopefully) macOS :+1:
