### ISSUE TITLE
timezone problem, even if you use a proxy

### ISSUE THREAD

**Issue by tserebour** [daijro/camoufox#5]
The timezone doesn't change even if you use a proxy.

**Comment by daijro** [comment]
Hello, timezone spoofing has been added in v130.0.1-beta.7.

I will look into adding a geoip/timezone database into the Python library to help find and pass in timezone information that matches your IP.

**Comment by daijro** [comment]
In 2.0.0, timezones will now be automatically calculated with respect to the proxy when `geoip` is enabled.
