### ISSUE TITLE
winerror

### ISSUE THREAD

**Issue by satanmp** [daijro/camoufox#54]
### Describe the bug:

run camoufox in thread

### Screenshots:

![图片](https://github.com/user-attachments/assets/45e5ea86-1125-4683-97bf-44d811a00c97)

### To Reproduce:

Provide steps or a code snippet that reproduces the bug.

### Version:

beat.12

**Comment by daijro** [comment]
Hi, could you provide a snippet that reproduces the bug?

From the error, this seems to be happening because Camoufox was closed during its launch process.

**Comment by satanmp** [comment]
> Hi, could you provide a snippet that reproduces the bug?
> 
> From the error, this seems to have happened because Camoufox was closed during its launch process.

I changed a computer and it worked. It might be a network problem.thank you
