### ISSUE TITLE
Unable to load local add-on .xpi file (no error, but extension doesn't appear)

### ISSUE THREAD

**Issue by collynash** [daijro/camoufox#55]
### Describe the bug:

Per the documentation: https://camoufox.com/fingerprint/addons/ I should be able to use add ons as follows:

```python
from camoufox.sync_api import Camoufox

with Camoufox(addons=['/path/to/addon', '/path/to/addon2']) as browser:
    page = browser.new_page()
```

The array addons argument should be a path to a folder that contains .xpi extensions. If you point to a xpi file directly as the full path this will cause an [error](https://github.com/daijro/camoufox/blob/732d7bac8dd319e61a10759e52c639b2f1586a9c/pythonlib/camoufox/addons.py#L56).

When I include an add on, and launch a headful browser, I do not see it added and the code produces no errors.

One thing I notice is the default add ons loaded are URLs direct to XPI files.

### Version:
> Camoufox:       v130.0.1-beta.12

**Comment by daijro** [comment]
Hello,

To load an `.xpi` file, rename it to a `.zip` file, extract it, and pass the extracted folder.

I've added clearer documentation and addon error handling in 0.3.3 to prevent confusion in the future :+1:
