### ISSUE TITLE
how can i specify different user directories so that I can open multiple browsers, just like Chrome's --user-data-dir.

### ISSUE THREAD

**Issue by zgc-zgc** [daijro/camoufox#56]
how can i specify different user directories so that I can open multiple browsers, just like Chrome's --user-data-dir.

**Comment by netdev1** [comment]
I think you have to launch it with `persistent_context=True` and `user_data_dir=/your/dir/path/`

**Comment by daijro** [comment]
> I think you have to launch it with `persistent_context=True` and `user_data_dir=/your/dir/path/`
> 
> you can look into the changes made here #21

Correct, thanks for your answer!

Here's an example:

```python
with Camoufox(
    persistent_context=True,
    user_data_dir='/path/to/profile/dir',
) as browser:
    page = browser.new_page()
    ...
```

**Comment by zgc-zgc** [comment]
thank you all!

**Comment by AkhilAvasarala022** [comment]
@zgc-zgc did that works for you
