### ISSUE TITLE
Browser window size

### ISSUE THREAD

**Issue by Moljave** [daijro/camoufox#58]
Hi, after reinstalling the windows,when i start the browser it takes a random window size, what could be the problem? This code used to work fine before.

device = {.
    
‘navigator.platform’: ‘Linux i686’,
    ‘navigator.hardwareConcurrency’: 8,
    ‘navigator.product’: ‘Gecko’,
    
‘navigator.maxTouchPoints’: 5,

}
   
async def init_browser(self):
    proxyClient = self.GetProxyFromString( self.proxy)
    self.browser = AsyncCamoufox(headless=False,config=device,i_know_what_im_doing=True)
    await self.browser.start()
    self.page = await self.browser.browser.new_page(proxy=proxyClient,viewport={‘width’: 550, ‘height’: 750})

Playwright version 1.48.0
Camoufox version 3.3

**Comment by MaxAndolini** [comment]
Use Window property in camoufox.

**Comment by daijro** [comment]
From the docs:

> `window`
> Type: Optional[Tuple[int, int]]
>
> Set the window size in (width, height) pixels. This will also set the window.screenX and window.screenY properties to position the window at the center of the generated screen.
> ```py
> with Camoufox(window=(1282, 955)) as browser:
>    ...
> ```
