### ISSUE TITLE
It seems that the setting for 'Open links in tabs instead of new windows' is not working. In my case below, it opens two windows. The code is as follows:

### ISSUE THREAD

**Issue by zgc-zgc** [daijro/camoufox#60]
It seems that the setting for 'Open links in tabs instead of new windows' is not working. In my case below, it opens two windows. The code is as follows:

page = browser.pages[0]
await page.goto("https://browserscan.net")
new_page = await browser.new_page()
await new_page.goto("https://example.com")

**Comment by Nongzhsh** [comment]
Maybe this is by design? I tried it with PW, and it also opens two windows.

**Comment by daijro** [comment]
This is by PW's design. If pages were to open in tabs of the same window, you'd only be able to interact with the page in the active tab.
