### ISSUE TITLE
Not working on Python 3.8 now

### ISSUE THREAD

**Issue by D4Vinci** [daijro/camoufox#61]
First of all thanks for your great work here. It's really a genius idea and brilliant work!

### Describe the bug:

I'm using Camoufox on my package so the automated tests that are done by GitHub Actions on Python 3.8 failed while installing it with this error:

```
../.tox/py/lib/python3.8/site-packages/camoufox/__init__.py:2: in <module>
    from .async_api import AsyncCamoufox, AsyncNewBrowser
../.tox/py/lib/python3.8/site-packages/camoufox/async_api.py:11: in <module>
    from camoufox.virtdisplay import VirtualDisplay
../.tox/py/lib/python3.8/site-packages/camoufox/virtdisplay.py:14: in <module>
    from camoufox.pkgman import OS_NAME
../.tox/py/lib/python3.8/site-packages/camoufox/pkgman.py:29: in <module>
    ARCH_MAP: dict[str, str] = {
E   TypeError: 'type' object is not subscriptable
```

I see the reason is that you are using `dict` instead of `typing.Dict`, which Python versions do not allow before 3.9.
Fortunately, the fix is easy just use `typing.Dict` instead of `dict` and `typing.List` instead of `list`.
Check out this [thread](https://stackoverflow.com/a/75202688/5055936)

### To Reproduce:

After installing it on Python 3.8, do `from camoufox.sync_api import Camoufox`

### Version:

0.3.4

**Comment by daijro** [comment]
Thanks! Seems like I forgot to enable eval annotations in my [vermin](https://github.com/netromdk/vermin) tests and missed this.

Fix has just been added in 0.3.5 :+1:

**Comment by D4Vinci** [comment]
Hi mate, you forgot `dict` in line [29](https://github.com/daijro/camoufox/blob/692e8a162c59735157366338afa9c2ad9bfd47a7/pythonlib/camoufox/pkgman.py#L29C11-L29C15).
Also, I see it in lines 166 and 443.
It still doesn't work on Python 3.8 because of line 29 but fixing it will trigger the other lines too.

**Comment by D4Vinci** [comment]
vermin didn't detect it on my machine too for some reason so it's better if you just search all files with lowercase `dict`

**Comment by daijro** [comment]
My bad, I've gone through and replaced every instance of `dict` to `Dict` in 0.3.6. Should hopefully work now.

**Comment by D4Vinci** [comment]
I can confirm from my end. All tests passed on Python 3.8 now 🎉 
Thanks!
