### ISSUE TITLE
Hide all progress bars

### ISSUE THREAD

**Issue by D4Vinci** [daijro/camoufox#65]
### Describe the feature:

Hi, I appreciate that this library is still not ready for production, but can't we have a verbose mode to hide all progress bars, like these?

<img width="2029" alt="Screenshot 2024-11-02 at 4 16 35 PM" src="https://github.com/user-attachments/assets/52968aa9-a05f-4067-9e71-83d5ec01e959">

I think it's better to have a command line like `camoufox fetch` to download all browserforge files and the rest. I plan to use Camoufox inside a web scraping library, so having progress bars would definitely hurt the user experience for your library and mine.

I think adding all this logic inside `camoufox fetch` would be even better (like `browserforge update` for example)

**Comment by daijro** [comment]
Hello,

In the latest commit, default addons are now downloaded on `camoufox fetch`. I've also removed the unnecessarily verbose progress bars when downloading addons.

**Comment by D4Vinci** [comment]
Nice work dude! Let's close this ticket then.
