### ISSUE TITLE
Fingerprint enhancement

### ISSUE THREAD

**Issue by 2516455367** [daijro/camoufox#73]
How to switch between various fingerprints and proxies on an already opened page. This is important.

**Comment by daijro** [comment]
Hello,

Switching between fingerprints on an already opened page isn't/likely won't be supported. A workaround for you could be to save your cookies and open a new Camoufox browser, then inject your cookies and load the page.

It is not possible to switch between proxies on an opened page (this is an inherit limitation of both Firefox and Playwright).
