### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by namename-123** [daijro/camoufox#74]
### Describe the bug:

Hello, I've tried using a custom user_dir with camoufox in hope it uses the cached assets for faster browsing but that doesn't seem to work.

### To Reproduce:
```
with Camoufox(
    os=['windows'], 
    humanize=2.0,
    persistent_context=True,
    screen=constrains,
    user_data_dir=os.getcwd() + '/cache_storage_firefox'
    ) as browser:

    page = browser.new_page()
    page.goto("https://abrahamjuliot.github.io/creepjs/")
    input('')
    browser.close()
```
### Version:

v132.0-beta.15

I've tried the same strategy with playwright chromium and it worked well enough, but here it doesn't. Could it be a preferences issue?

**Comment by daijro** [comment]
Hello,

I've added an `enable_cache` method that reverts Camoufox's cache preferences in 0.3.9. Hope this helps.
