### ISSUE TITLE
[BUG] switch tab by mouse is broken

### ISSUE THREAD

**Issue by tobwen** [daijro/camoufox#8]
### description
Tabs can be switched by click (also the close, pin, etc. buttons are gone, but maybe that's by design).

### screen recording
![tab-switch](https://github.com/user-attachments/assets/f450ddf2-9017-4ac4-887e-c961feb4ade2)
![switch-tab](https://github.com/user-attachments/assets/63fc477c-a8b2-4e27-b397-17212fe5fc40)

### affected versions
v129, v130

**Comment by daijro** [comment]
Hello,

Camoufox is only meant to be ran programmatically--any manual user action to tabs were removed to prevent unintentional interference with Playwright's actions or any issues dragging around the window.

Tab switching is still possible with Alt+Tab, but I can add the tab clicking functionality back though, if manually using Camoufox was something you're interested in.

**Comment by tobwen** [comment]
> Camoufox is only meant to be ran programmatically--any manual user action to tabs were removed to prevent unintentional interference with Playwright's actions or any issues dragging around the window.

Oh sorry. I used it for interactive debugging before scraping.
 
> Tab switching is still possible with Alt+Tab, but I can add the tab clicking functionality back though, if manually using Camoufox was something you're interested in.

No, no! No need for additional work. I misunderstood and thought it was a bug :-)

It was my fault and I'm closing this. Thanks for your good work!
