### ISSUE TITLE
[QUESTION] It's possible to run camoufox inside containers?

### ISSUE THREAD

**Issue by chrisemke** [daijro/camoufox#88]
I'm having some issues to run camoufox inside containers docker/podman.

I wish to know if it's a current limitation of this project or it's just my issue.

currently I run playwright very well in websites that don't need any anti-bot strategies.

Thanks!

"playwright>=1.48.0"
"camoufox[geoip]>=0.3.8"

**Comment by daijro** [comment]
Hello, this is possible. Here is the Dockerfile that I use to benchmark Camoufox:

```dockerfile
FROM debian:latest

# Set working directory
WORKDIR /app

# Install Python and other tools
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    xvfb \
    && apt-get clean

# Install Playwright dependencies & Camoufox
RUN pip3 install --no-cache-dir camoufox[geoip] --break-system-packages && \
    playwright install-deps && \
    python3 -m camoufox fetch

# Copy the benchmark script
COPY benchmark.py /app/

# Default entrypoint to the script
ENTRYPOINT ["python3", "/app/benchmark.py"]
```
Make sure you're using headless mode, or headless="virtual" to use xvfb :+1:

**Comment by daijro** [comment]
Here are some additional packages you may need if running on a lighter image:

https://camoufox.com/python/installation/#download-the-browser
