### ISSUE TITLE
setting screen.width, screen.height is invalid 

### ISSUE THREAD

**Issue by winner-hue** [daijro/camoufox#89]
camoufox = 0.3.10, firefox=132
website: https://www.browserscan.net/
code: 
class ScreenInfo(Screen):
    min_width = 1055
    max_width = 1920
    min_height = 960
    max_height = 1080

fg = FingerprintGenerator()
fire = fg.generate(screen=ScreenInfo(), os='windows', browser='firefox', device='desktop')
fire.videoCard.vendor = 'Google Inc. (Intel)'
fire.videoCard.renderer = 'ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar'
fire.screen.width = 1920
fire.screen.height = 1080

with Camoufox(
        geoip=True,
        proxy={
            "server": "http://127.0.0.1:7890",
            "username": None,
            "password": None
        },
        os=["windows", "macos", "linux"],
        allow_webgl=True,
        i_know_what_im_doing=True,
        # humanize=2.0,
        fingerprint=fire,
        config={
            "navigator.language": "en",
            "navigator.languages": ["en", 'en'],
            "screen.width": 1920,
            "screen.height": 1080,
            "window.outerHeight": 1040,
            "window.outerWidth": 1920,
            'webrtc:ipv4': '188.253.4.94',
            'webrtc:ipv6': '',
            "timezone": "Asia/Singapore"
            # "webgl.disable": True
        },
        screen=Screen(min_width=1920, min_height=1080, max_width=1920, max_height=1080),
        window=(1920, 1080)
) as browser:
    page = browser.new_page()
    page.goto("https://www.browserscan.net/")

screenshot： 
![image](https://github.com/user-attachments/assets/88e6c5a5-4e77-4aa4-875e-ab7185d40583)

question：
 I have tried many times, but the width and height of the screen cannot be changed. How should I deal with this?

**Comment by winner-hue** [comment]
also，I modified the GPU information and it didn't take effect
![image](https://github.com/user-attachments/assets/d40b5d88-be8f-418b-bcda-53ec3277f453)

**Comment by winner-hue** [comment]
Regarding setting the width and height of the screen, I understand that you may have misunderstood what I meant.

**Comment by daijro** [comment]
Fixed in latest release.
