### ISSUE TITLE
[BUG] in light skin menus become unreadable

### ISSUE THREAD

**Issue by tobwen** [daijro/camoufox#9]
### description
My old monitor can't handle dark mode - I can hardly see anything. When turning on the light mode with the bright theme, the context menus become unreadable.

### screenshot
![image](https://github.com/user-attachments/assets/6b1a5a60-31ad-4e94-9dbb-b5d0ea86e36a)

### affected versions
v129, v130

**Comment by daijro** [comment]
Fixed in v130.0.1-beta.6
