### ISSUE TITLE
Getting detected by Impreva

### ISSUE THREAD

**Issue by D4Vinci** [daijro/camoufox#90]
### Website detecting Camoufox:

What website or WAF is flagging Camoufox? Provide as much detail and additional context as possible.

According to Wappalyzer, it's Impreva.

### Screenshots:

Most of the time it just gives a blank white page but sometimes if you are patient enough, you will see this page:

<img width="797" alt="Screenshot 2024-11-20 at 1 49 25 PM" src="https://github.com/user-attachments/assets/22bd354e-4866-462a-8ef0-2ff6c7c9c6bc">

Playing around and disabling the JS give this too (if helpful):

<img width="1028" alt="Screenshot 2024-11-20 at 1 50 50 PM" src="https://github.com/user-attachments/assets/edc568a4-1c8e-4bd1-af2d-5ed2341c9a63">

### To Reproduce:

Send a testing site that reproduces the issue, and a snippet of your script. Provide your `Camoufox()` or `AsyncCamoufox()` initialization.

Just browse this page https://www.smythstoys.com/uk/en-gb/toys/lego-and-bricks/c/SM060107
The example doesn't matter because I always get blocked locally and with different configs.

### Other questions:

These questions will help me diagnose the issue:

1. Are you using a proxy?

No

2. Open the website in a private tab in your personal browser using the same IP. Does it work?

Yes

3. Is Camoufox detected randomly or every time?

Every time

4. What OS are you using?

MacOS

### Version:

Run `python -m camoufox version` in your terminal and paste the output here.
```
Pip package:	v0.3.10
Camoufox:	v132.0-beta.15 (Up to date!)
```

---
Also, congratulations on finally getting some of the recognition Camoufox deserves. I made sure everyone knows I'm using your work in [Scrapling](https://github.com/D4Vinci/Scrapling) even in my Reddit post and then happily watched the stars go up haha.

**Comment by D4Vinci** [comment]
It only worked when I used the `allow_webgl` parameter locally, I will test it on the server ASAP.

**Comment by daijro** [comment]
Hello, thanks for integrating my work into Scrapling! I appreciate the recognition!

---

Thank you for the valuable test site.

From my debugging, it seems that other similar open source anti-detect libraries like Patchright that also use the PW scoping strategy aren't able to pass this site as well.
 
I haven't been able to produce a success case by enabling WebGL.

Here are a couple notes from my research this morning:
- The website doesn't flag when launching the Camoufox binary directly and navigating to the site, which leads me to believe that this is an automation detection.
- Running a fresh build of Camoufox _without_ Playwright's patches applied still seems to fail. This might have something to do with the Firefox remote automation API causing a leak.

I'll keep you updated — I'm between classes right now, but I'll continue investigating this ASAP.

**Comment by D4Vinci** [comment]
Nice notes! I have a friend who was able to make camoufox work by enabling WebGL as well on his machine. He was getting blocked before on his personal browser (brave) but the website worked with him on Opera which was weird because both browsers are based on Chromium as you know.

**Comment by daijro** [comment]
Hello, here's an update. I found 3 things Imperva has started detecting:

- Your friend is right — WebGL does seem to be required now (which is weird, a couple hours ago I was able to load the page without it. Maybe I'm going crazy). In the next update, WebGL will be enabled in Camoufox by default, although it might hurt fingerprintability. Developing WebGL spoofing is now very high priority.
- It seems I was right about it being FF's automation API being detected. On a fresh build, FF is flagged when a client connects to the debug server. In Camoufox, the python library uses the FF rdp API to upload addons like uBlock Origin. I will work on a new way to load addons.
- The third thing that Imperva detects is Camoufox's build config listed [here](https://github.com/daijro/camoufox/blob/main/assets/base.mozconfig). I've narrowed it down to the patched locales that Camoufox uses to rebrand from Firefox. One of these locales is likely leaking to the page.

I'm also starting to believe that this repo is being monitored. I may have to start closing the source to certain patches in the future.

---

After a bit of research, I've successfully fixed all the leaks in a local build:

![image](https://github.com/user-attachments/assets/75e6953b-78ed-41e3-86a8-f92a2621bca7)

**Comment by D4Vinci** [comment]
Impressive work @daijro !
Yeah definitely the repo is monitored it’s their job and with time while the project becoming more famous more protection companies will see it

**Comment by D4Vinci** [comment]
Hey @daijro, it just came to my mind: Why won't you make installing UBO optional? It has nothing to do with fingerprinting anyway, and now it hurts Camoufox. I see it isn't worth all the time you will waste researching a new way to install add-ons. If the user chooses to install an add-on, give him/her a leak warning.

**Comment by daijro** [comment]
> Hey @daijro, it just came to my mind: Why won't you make installing UBO optional?

UBO helps a lot with memory load on bigger websites (for example, on Yahoo.com its almost a 50% memory reduction) so I see it as pretty valuable to keep, especially if Camoufox is going to be run on datacenters.

It shouldn't be too hard to implement addon loading. It's just a quick call to the AddonActor API that I can implement elsewhere (for example browser-init.js) to install the addon when the browser starts:

```js
  async installTemporaryAddon(addonPath, openDevTools) {
    let addonFile;
    let addon;
    try {
      addonFile = new FileUtils.File(addonPath);
      addon = await AddonManager.installTemporaryAddon(addonFile);
    } catch (error) {
      throw new Error(`Could not install add-on at '${addonPath}': ${error}`);
    }

    Services.obs.notifyObservers(null, "devtools-installed-addon", addon.id);
```

https://searchfox.org/mozilla-central/source/devtools/server/actors/addon/addons.js#28

**Comment by daijro** [comment]
Addon loading has just been added 👍

Beta.17 is now building. I'll work on an update for the Python library in a bit

**Comment by daijro** [comment]
Camoufox beta 17 & python release 0.4.1 is now out.

This includes all the fixes listed here, and WebGL fingerprint rotation.

**Comment by daijro** [comment]
There seems to be an issue on some devices where certain WebGL fingerprints crash the browser when injected. WebGL rotation has been temporarily rolled back. I'm going to reopen this issue until it's fixed.

**Comment by D4Vinci** [comment]
Hi mate, impressive work!
Unfortunately, some issues came with the update, I'm testing on the same website with WebGL enabled and sometimes disabled. Sometimes the website works but sometimes I get this with WebGL disabled
<img width="1934" alt="Screenshot 2024-11-22 at 11 25 47 AM" src="https://github.com/user-attachments/assets/64a5dd8a-954d-46a1-a9b9-c79434eb41f3">

and sometimes I get a full crash with WebGL enabled
<img width="1249" alt="Screenshot 2024-11-22 at 11 27 58 AM" src="https://github.com/user-attachments/assets/99a08a18-51b3-400a-8059-80b48c2e6a0d">

**Comment by daijro** [comment]
> Hi mate, impressive work!
> Unfortunately, some issues came with the update, I'm testing on the same website with WebGL enabled and sometimes disabled. Sometimes the website works but sometimes I get this with WebGL disabled
> <img width="1934" alt="Screenshot 2024-11-22 at 11 25 47 AM" src="https://github.com/user-attachments/assets/64a5dd8a-954d-46a1-a9b9-c79434eb41f3">
> 
> and sometimes I get a full crash with WebGL enabled
> <img width="1249" alt="Screenshot 2024-11-22 at 11 27 58 AM" src="https://github.com/user-attachments/assets/99a08a18-51b3-400a-8059-80b48c2e6a0d">
> retrying the code in the second error again right away gets no crash
> 
> 
> 

I noticed this too when I was testing it on a different device. When I was testing it on my PC, I didn't notice any issues with it when I was testing the release, but on my laptop it would frequently crash with certain fingerprints from GPU vendors that clashed with my own. My theory is that when an GL enum is overriden thats reserved for an internal binding it causes a panic.

I've rolled back WebGL fingerprint rotation in 0.4.2 to work on a fix. It's probably best to disable WebGL for sites that don't require it as well, as it can be used to tell if you're lying about your OS.

**Comment by daijro** [comment]
Got it. WebGL is disabled by default again until beta 18 is out. I need to test on more devices.

**Comment by D4Vinci** [comment]
Alright mate, good luck!

**Comment by D4Vinci** [comment]
Hey mate, check this from the new Playwright version it might help:
https://github.com/microsoft/playwright/issues/33566

**Comment by daijro** [comment]
Hello,

WebGL fingerprint rotation has been fixed in v0.4.4-beta. The issue was with some of the fingerprints in the database having bad data.

I have ran tests with each fingerprint, and it seems to be working now. Camoufox is having no issues passing Creepjs's WebGL fingerprint tests.

However, before I release v0.4.4, I will add better type validation for nested values to be absolutely sure that bad data isn't being sent to the browser. :+1:

**Comment by D4Vinci** [comment]
Brilliant! Nice work bro!

**Comment by daijro** [comment]
0.4.4 is now out of beta, and WebGL fingerprint injection is enabled by default.

Camoufox also now has a [better config validator](https://github.com/daijro/camoufox/tree/main/jsonvv) that can be used to check user configurations for potential leaks/mismatched values or broken data using the [properties.jvv](https://github.com/daijro/camoufox/blob/main/settings/properties.jvv) file that will be shipped with newer Camoufox releases.

I'll go ahead and close this issue now, however, please let me know if you're experiencing issues related to WebGL detection again.

**Comment by D4Vinci** [comment]
@daijro Amazing work bro, I have just tested it too and all looks perfect from my side!

**Comment by halvorstein** [comment]
I'm trying to scrape the same page (https://www.smythstoys.com/uk/en-gb/toys/lego-and-bricks/c/SM060107) and the process seems to be blocked again.
The response I'm getting is:
```
<!DOCTYPE html><html><head>
        <noscript>
            <title>Pardon Our Interruption</title>
        </noscript>

        <meta name="viewport" content="width=1000">
        <meta name="robots" content="noindex, nofollow">
        <meta http-equiv="cache-control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="expires" content="0">

        <style>
            .container { max-width: 800px; margin: auto; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; color: #7a838c; }
            h1 { color: #2a2d30; font-weight: 500; }
            li { margin: 0 0 10px; }
            a { color: #428bca; }
            a:hover, a:focus { color: #2a6496; }
        </style>

        <script>
          var isSpa = new URLSearchParams(window.location.search).get('X-SPA') === '1' || window.isImpervaSpaSupport;
        </script>

        <!-- This head template should be placed before the following script tag that loads the challenge script -->
        <script>
          window.onProtectionInitialized = function(protection) {
            if (protection && protection.cookieIsSet && !protection.cookieIsSet()) {
              showBlockPage();
              return;
            }
            if (!isSpa) {
              window.location.reload(true);
            }
          };
          window.reeseSkipExpirationCheck = true;
        </script>

        <script>
          if (!isSpa) {
            var scriptElement = document.createElement('script');
            scriptElement.type = "text/javascript";
            scriptElement.src = "/onalbaine-legeance-what-come-Womany-Malcome-to-o/6292324293707956376?s=SAe6YFPE";
            scriptElement.async = true;
            scriptElement.defer = true;
            document.head.appendChild(scriptElement);
          }
        </script><script type="text/javascript" src="/onalbaine-legeance-what-come-Womany-Malcome-to-o/6292324293707956376?s=SAe6YFPE" async="" defer=""></script>
        <script type="text/javascript">if (sessionStorage) { sessionStorage.setItem('distil_referrer', document.referrer); }</script>
    </head>
    <body>



        <div class="container" style="display: none;">
            <script>document.getElementsByClassName("container")[0].style.display = "none";</script>

            <h1>Pardon Our Interruption</h1>
<p>As you were browsing something about your browser made us think you were a bot. There are a few reasons this might happen:</p>
<ul>
<noscript><li>You've disabled JavaScript in your web browser.</li></noscript>
<li>You're a power user moving through this website with super-human speed.</li>
<li>You've disabled cookies in your web browser.</li>
<li>A third-party browser plugin, such as Ghostery or NoScript, is preventing JavaScript from running. Additional information is available in this <a title="Third party browser plugins that block javascript" href="http://ds.tl/help-third-party-plugins" target="_blank">support article</a>.</li>
</ul>
<p>To regain access, please make sure that cookies and JavaScript are enabled before reloading the page.</p>


        </div>
        <script>
          function showBlockPage() {
            document.title = "Pardon Our Interruption";
            document.getElementsByClassName("container")[0].style.display = "block";
          }

          if (isSpa) {
            showBlockPage();
          } else {
            window.interstitialTimeout = setTimeout(showBlockPage, 10000);
          }
        </script>


</body></html>
```

I'm using a datacenter IPv4 address, if that matters.

**Comment by D4Vinci** [comment]
@halvorstein Just don't disable resources mate. This error happens when you disable them or disable JS. Also, of course, the IP matters, protections can know easily that the request is coming from a datacenter IP, not a residential one!

**Comment by halvorstein** [comment]
> @halvorstein Just don't disable resources mate. This error happens when you disable them or disable JS. Also, of course, the IP matters, protections can know easily that the request is coming from a datacenter IP, not a residential one!

I'm running a minimal example with the following code and same results:
```
#!/usr/bin/env python3

from camoufox.sync_api import Camoufox


with Camoufox(headless=True) as p:
    page = p.new_page()
    page.goto(url="https://www.smythstoys.com/uk/en-gb/toys/lego-and-bricks/c/SM060107", wait_until="networkidle", timeout=0)
    content = page.content()
    print(content)
    p.close()
```

I'm using a headless remote Debian VPS. Should I do something differently?
