### ISSUE TITLE
Javascript or another code to send token Hcapcha 

### ISSUE THREAD

**Issue by DeathJoh** [daijro/camoufox#95]
Hello, Daijro, and thank you in advance for your work. I would like to ask you for some alternative to javascript or integrate some hcapcha solver. Wow, all the extensions I use are detectable. I wanted to try the token here, but wow, it can't be passed without javascript.

I'm solving hcaptcha and need to pass the token in some way.

This is done in selenium code using javascript 

```
driver.execute_script("""
document.getElementsByName('h-captcha-response')[0].style.display = 'block';
document.getElementsByName('h-captcha-response')[0].value = arguments[0];
""", token)
```

But how do I do it? Camoufox. Thank you.

**Comment by vlrevolution** [comment]
Can't you use javascript with camoufox?

**Comment by daijro** [comment]
Hello,

Using the Camoufox Python library, you can inject code into the main world like this:

https://camoufox.com/python/main-world/#modifying-the-dom---main-world

> This is done in selenium code using javascript

Selenium isn't officially supported by Camoufox. You can use the Camoufox library instead, which wraps around the Playwright API.
