### ISSUE TITLE
block_webrtc

### ISSUE THREAD

**Issue by DeathJoh** [daijro/camoufox#96]
### Describe the bug:
`block_webrtc = True    `

no working have this eror 

`BrowserType.launch() got an unexpected keyword argument 'block_webgl`

### To Reproduce:

```
        constrains = Screen(max_width=1620, max_height=1080)
        async with AsyncCamoufox(block_webgl = True,os=["windows", "macos", "linux"],block_images=False,block_webrtc=True, humanize=0.5, screen=constrains) as browser:
            page = await browser.new_page()
            await page.goto(url)

```
Provide steps or a code snippet that reproduces the bug.

### Version:
Pip package:    v0.3.10
Camoufox:       v132.0.2-beta.17 (Up to date!)

![image](https://github.com/user-attachments/assets/5ec9e60e-21ba-4fde-aafe-fccebbbe8821)

**Comment by daijro** [comment]
Hello, please run `pip install -U camoufox`.

**Comment by DeathJoh** [comment]
yes thanx working now good job :)
