### ISSUE TITLE
after upgrade,not work

### ISSUE THREAD

**Issue by julycreator** [daijro/camoufox#98]
### Describe the bug:

error:manifest.json is missing. Addon path must be a path to an extracted addon

### Screenshots:

![image](https://github.com/user-attachments/assets/6ddc4520-db77-4a16-9ff9-bbf8d52d6cfd)

### To Reproduce:

fg = FingerprintGenerator(browser=('chrome', 'firefox', 'safari', 'edge'), locale=('zh-CN', 'zh',),
                                  os=('windows', 'macos'), )

        with Camoufox(fingerprint=fg.generate(), headless=True, geoip=public_ip,i_know_what_im_doing=True,
                      proxy={"server": proxy_ip},
                      config={
                          "locale:language": "zh-CN,zh",
                          'webrtc:ipv4': public_ip,
                          'geolocation:latitude': latitude,
                          'geolocation:longitude': longitude,
                      },
                      humanize=True,
                      block_webgl=True,
                      ) as browser:
                page = browser.new_page()

                page.goto("https://www.google.com/",timeout=30000)

### Version:

beta.17

**Comment by Nongzhsh** [comment]
Hello, try to update the camoufxo package.
`pip install -U camoufox`

**Comment by julycreator** [comment]
> Hello, try to update the camoufxo package. `pip install -U camoufox`

the error is the same. not change

manifest.json is missing. Addon path must be a path to an extracted addon.

how to rollback?

**Comment by daijro** [comment]
> > Hello, try to update the camoufxo package. `pip install -U camoufox`
> 
> the error is the same. not change
> 
> manifest.json is missing. Addon path must be a path to an extracted addon.
> 

Your downloaded addons are likely corrupted.

You may need to run `camoufox remove` then `camoufox fetch`.

**Comment by julycreator** [comment]
> > > Hello, try to update the camoufxo package. `pip install -U camoufox`
> > 
> > 
> > the error is the same. not change
> > manifest.json is missing. Addon path must be a path to an extracted addon.
> 
> Your downloaded addons are likely corrupted.
> 
> You may need to run `camoufox remove` then `camoufox fetch`.

thank you ,It's work.
