### ISSUE TITLE
Getting Detected by Cloudflare

### ISSUE THREAD

**Issue by FayzulSaimun** [daijro/camoufox#99]
### Website detecting Camoufox: https://noxtools.com/

What website or WAF is flagging Camoufox? Provide as much detail and additional context as possible.
Previously camoufox was able to open the site solving the challenge. Now it reloads the challenges few times and then stuck at "Verify You're Human"
### Screenshots:
![image](https://github.com/user-attachments/assets/c7ac7aff-44d9-48c4-9838-eebefc1610f3)

### To Reproduce:
```
import time
from camoufox.sync_api import Camoufox

with Camoufox(headless=False, humanize=True) as browser:
    page = browser.new_page()
    page.goto('https://noxtools.com/')
    time.sleep(60)
```
Send a testing site that reproduces the issue, and a snippet of your script. Provide your `Camoufox()` or `AsyncCamoufox()` initialization.

### Other questions:

These questions will help me diagnose the issue:

1. Are you using a proxy?
Yes, Good residential proxies. Even without Proxies it gets detected.

2. Open the website in a private tab in your personal browser using the same IP. Does it work?
Yes, it works

3. Is Camoufox detected randomly or every time?
Every time recently. Previously it was working perfectly with proxies and was able to bypass the challenge 95% time.

4. What OS are you using?
Windows 11

### Version:
`Pip package:    v0.4.3`
`Camoufox:       v132.0.2-beta.17 (Up to date!)`
Run `python -m camoufox version` in your terminal and paste the output here.

**Comment by daijro** [comment]
This is likely related to #90.

Try enabling WebGL with `block_webgl=False`. This will fix the issue :+1: 

A fix for WebGL fingerprint injection should be out within a couple of days.

**Comment by daijro** [comment]
WebGL is now enabled by default. Closing this issue
